apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "bishalakstestv15-92d2"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "bishalakstestv15-92d2"
    spec:
      containers:
        - name: "bishalakstestv15-92d2"
          image: "bishalakstestacr.azurecr.io/bishalakstestv15"
          ports:
          - containerPort: 80