on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrbmwniv2zczfvu.azurecr.io
        username: ${{ secrets.acr_acrbmwniv2zczfvu_username }}
        password: ${{ secrets.acr_acrbmwniv2zczfvu_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Application/aspnet-core-dotnet-core" -f  "Application/aspnet-core-dotnet-core/Dockerfile" -t acrbmwniv2zczfvu.azurecr.io/bishalakstestv15:${{ github.sha }}
        docker push acrbmwniv2zczfvu.azurecr.io/bishalakstestv15:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_bishalakstestv15_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep bishalakstestv1588f2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace bishalakstestv1588f2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: bishalakstestv1588f2
        container-registry-url: acrbmwniv2zczfvu.azurecr.io
        container-registry-username: ${{ secrets.acr_acrbmwniv2zczfvu_username }}
        container-registry-password: ${{ secrets.acr_acrbmwniv2zczfvu_password }}
        secret-name: bishalakstesdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: bishalakstestv1588f2
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          acrbmwniv2zczfvu.azurecr.io/bishalakstestv15:${{ github.sha }}
        imagepullsecrets: |
          bishalakstesdockerauth